2019-06-27 10:55:05,037 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:54]
2019-06-27 10:56:15,918 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:54]
2019-06-27 10:57:15,486 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:54]
2019-08-11 17:56:08,199 INFO: Microblog startup [in C:\pandachef\microblog\app\__init__.py:54]
2019-08-11 18:05:02,527 INFO: Microblog startup [in C:\pandachef\microblog\app\__init__.py:54]
2019-08-11 18:05:11,865 INFO: Microblog startup [in C:\pandachef\microblog\app\__init__.py:54]
2019-08-11 18:15:39,961 INFO: Microblog startup [in C:\pandachef\microblog\app\__init__.py:54]
2019-08-11 18:19:13,724 INFO: Microblog startup [in C:\pandachef\microblog\app\__init__.py:54]
2019-08-11 18:19:30,415 INFO: Microblog startup [in C:\pandachef\microblog\app\__init__.py:54]
2019-08-11 18:22:22,983 INFO: Microblog startup [in C:\pandachef\microblog\app\__init__.py:54]
2019-08-11 19:16:11,144 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-19 22:55:22,720 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-19 23:08:37,208 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-19 23:12:32,090 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-19 23:16:49,355 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 15:48:11,140 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 15:54:07,171 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 15:54:51,441 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 15:56:40,792 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 15:56:45,551 ERROR: Exception on /recipe/Пирожок с олениной [POST] [in c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\python\git\microblog\app\routes.py", line 256, in recipe
    isBreakfast = form.name.isBreakfast
AttributeError: 'StringField' object has no attribute 'isBreakfast'
2019-11-24 15:57:32,797 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
